version: "3.9"

services:
  backend:
    container_name: personal_website-backend
    build: ./personal_website
    volumes:
      - ./personal_website:/app/personal_website
    ports:
      - 8000:8000
    env_file:
      - ./personal_website/.env.dev
